#pragma once

#include <cstddef>

#define DATATYPE_UNSIGNED_INT 2
#define DATATYPE_UNSIGNED_SHORT 3
#define DATATYPE_FLOAT32 4

#define CLUTTER_RESISTANT_DISTANCE 314
#define HAMMING_DISTANCE 1213121
#define WEIGHTED_HAMMING_DISTANCE 418